ambassify/react-avatar

avatar.jsx

In my code I also calculate a hash of the name and use that as the index of the rnd color, so the same username gets the same color always. I can submit that patch also, but minimally, it should honor the color property as described in the docs.

Honor color property for background

---

package.json

stops deprecation warnings from legacy MD5—replaced with successor md5@2.0.0
see: https://github.com/pvorb/node-md5/commit/c018e8932d0fbb2a200a540a055da487f4f9c150

Remove deprecated MD5, replace with md5@2.0.0

---

src/sources/Facebook.js

Use both the width and height parameters when requesting the Facebook avatar from Graph API, this way Facebook returns the portrait/landscape image like the user has specified it should look when squared.
Only width:
Width + height:

[Facebook] use width and height for graph request

---

.babelrc
package.json

The `transform-runtime` plugin was installed but not being used. This results in not all ES2015 code being transpiled, leaving things like `Array.from` in the built library.
I also moved the actual `babel-runtime` dependency to dependencies because the built version requires code from that package. As a result, consuming packages need to install it too. (https://babeljs.io/docs/plugins/transform-runtime/)

[build] add babel-runtime transform

---

README.md
package.json

All react dependencies should be peerDependencies to avoid conflicting react versions in your build. It's a bit of a PITA that consumers have to manually install the `react-addon-shallow-compare` but if you don't do this, you get bugs like I describe below.
1. You have a project that uses React@0.14, but doesn't use `react-addon-shallow-compare`
2. `npm install --save react-avatar`
3. npm install `react-avatar` and the latest version of `react-addon-shallow-compare`, which is `>15`
4. The latest version of `react-addon-shallow-compare` needs React@15 and you end up getting __UNMET PEER DEPENDENCY__ errors.
Users now have two ways of solving that error:
1. Install react@15, which results in two react versions in your build
2. Install `react-addon-shallow-compare@0.14`, which is the right …

`react-*` should be peerDependencies

---

package.json
src/index.js

Fixes #66 
This change is not retro compatible, So you cant use it with  react < 0.15.3.
But React-addons-shallow-compare is a legacy react code.
Anyways if some wants to keep using 0.14.x react version can use older version of this plugin.

Replacing legacy shallow-compare with PureComponents

---

package.json

The engines field is causing yarn to stumble. I'm running node 9 and I can't install react-avatar without the `--ignore-engines` flag. Considering the plugin is already compiled to es5 do you mind if we just remove it?
```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error react-avatar@2.5.1: The engine "node" is incompatible with this module. Expected version "8.x.x".
error Found incompatible module
```

Remove engines field from package.json

---

README.md
build/demo.js
lib/demo.js
lib/index.js
lib/utils.js
src/demo.js
src/index.js
src/utils.js

Allow the unit in which the size should be measured to be supplied as
part of the `size` value.
Replaces https://github.com/Sitebase/react-avatar/pull/82
Resolves https://github.com/Sitebase/react-avatar/issues/57

[size] allow unit types in value

---

.travis.yml

Travis-CI is currently using node 0.10

[ci] fix node version on travis-ci

---

src/index.js

Return after call to setState src to null.  This will cause the state to be updated and then a fresh render to be evaluated after the new state has been set.  Otherwise the next source will be called and attempted, overwriting the state so that the image source is never null'd out and acted upon.

Fix for handling error resulting from bad image src url

---

README.md
build/demo.js
lib/demo.js
lib/index.js
src/demo.js
src/index.js

Extend the existing `round` property to allow for a custom borderRadius
on the avatar. When set to `false` now allows for CSS that manipulates avatar rounding.
Replaces https://github.com/Sitebase/react-avatar/pull/83

[round] allow custom radius

---

build/demo.js
lib/index.js
src/index.js

When doing something like the below, the custom className was being appended to without a space, therefore modifying it. Just added a space to fix this.
```
import Avatar from 'react-avatar';
<Avatar className="foo" name="John Smith" />
```
In the above example, `className` becomes `'foosb-avatar'` instead of `'foo sb-avatar'`

Don't modify existing className on outer element

---

README.md
build/demo.js
lib/cache.js
lib/context.js
lib/demo.js
lib/index.js
lib/sources/Google.js
lib/sources/Value.js
lib/sources/Vkontakte.js
lib/utils.js
src/cache.js
src/context.js
src/demo.js
src/index.js
src/sources/Google.js
src/sources/Value.js
src/sources/Vkontakte.js
src/utils.js

This PR adds a `ConfigProvider` which can be used to set the `cache`
used and the `colors` array from which random colors are chosen.
**ConfigProvider Usage:**
https://github.com/Sitebase/react-avatar/blob/8a207c1644eefade6f009b4f0f25ff5526965633/src/demo.js#L219-L229
**Cache API:**
https://github.com/Sitebase/react-avatar/blob/8a207c1644eefade6f009b4f0f25ff5526965633/src/cache.js#L12-L55
Resolves https://github.com/Sitebase/react-avatar/issues/73
Related to https://github.com/Sitebase/react-avatar/pull/67

[config] provide configuration context for react-avatar

---

index.d.ts

I was unable to import ConfigProvider and use it as an element in my code.
Getting "[ts] 'ConfigProvider' only refers to a type, but is being used as a value here."

export ConfigProvider as component

---

README.md
build/demo.js
lib/context.js
lib/demo.js
lib/sources/Value.js
lib/utils.js
src/context.js
src/demo.js
src/sources/Value.js
src/utils.js

This PR adds the `initials` property to the `ConfigProvider` and to `Avatar` which can be used to set a custom method for generating the initials shown by `react-avatar`.
**usage**
```js
function customInitials(name) {
return name.split(' ')
.map(part => part.substring(0, 1).toUpperCase())
.filter(v => /[A-Z]/.test(v))
.join('');
}
<ConfigProvider initials={customInitials}>
<Avatar name="Hello World" />
<Avatar name="Test User" />
</ConfigProvider>
<Avatar name="Hello World" initials={customInitials} />
<Avatar name="Hello World" initials="HFW" />
```
Resolves https://github.com/Sitebase/react-avatar/issues/81

[initials] Add support for custom initial methods

---

src/index.js

Src was added to state when the component loaded, this caused the
"next" (internal.fetch) handler to be called multiple times on error. Because of
this the initials source was skipped most times.

[src] Initials source was skipped sometimes.

---

package.json
webpack.config.js

This was causing issues as soon as we allowed babel to transform
builtins. This would cause import statements to appear next to
`module.exports` and trip up webpack when building the ES6 version.

[compat] Disable transpilation of node_modules

---

README.md
demo/index.js
index.d.ts
src/index.js

This is a proposal of a new way to manage font-size on text-based avatars.
The current implementation makes the **width of the text** match `avatarSize / textSizeRatio` but this results in a lot of different font sizes. This happens because when you're not using a monospaced font, "JJ" for example will be significantly narrowed than "WW". This causes font-sizes to very even between avatars that all have two initials. (see image)
My proposal returns it back to the old implementation where **font-size** is set as `avatarWidth / textSizeRatio`. The problem with that implementation was that avatars with three of four initials could overflow the avatar's background. I propose to solve this by adding a new property `textMarginRatio` which reduces font-size only when the text would become to …

improve font-size consistency with textMarginRatio property

---

src/index.js
src/utils.js

If a parent was not visible due to some parent having a `display: none`,
the text scaling will cause the font-size of the actual text value to
become `0px` and thus not be visible.
Resolves https://github.com/Sitebase/react-avatar/issues/159

[text scaling] fix scaling issue on hidden avatars

---

README.md
src/cache.js
src/index.js

This PR makes the default caching behavior configurable by exposing the default implementation as a class which takes `sourceTTL` and `sourceSize` as options.
```html
import Avatar, { Cache, ConfigProvider } from 'react-avatar';
const cache = new Cache({
// Keep cached source failures for up to 7 days
sourceTTL: 7 * 24 * 3600 * 1000,
// Keep a maximum of 20 entries in the source cache
sourceSize: 20
});
// Apply cache globally
<ConfigProvider cache={cache}>
<YourApp>
...
<Avatar name="Wim Mostmans" />
...
</YourApp>
</ConfigProvider>
// For specific instances
<Avatar name="Wim Mostmans" cache={cache} />
```
Resolves https://github.com/Sitebase/react-avatar/issues/161

[cache] Allow caching behaviour to be configurable

---

README.md
index.d.ts
src/index.js

Resolves https://github.com/Sitebase/react-avatar/issues/163

[img] Add support for custom alt tag.

---

index.d.ts

The typedefinitions for `AvatarRedirectSource` and `RedirectSource` were
incorrect.
Resolves https://github.com/Sitebase/react-avatar/issues/204

[typescript] fixes incorrect typedefinition

---

babel.config.js
package.json

- `@babel/plugin-transform-runtime` to turn the babel syntax helpers into require statements. This way the helpers are not duplicated in every file and can also be shared when react-avatar is installed in a larger project with other libraries that use the transform runtime.
- `babel-plugin-polyfill-corejs3` so polyfills use `core-js-pure` which doesn't pollute the global namespace and only polyfills the things that are needed based on the targets config

[build] use new babel tools to optimize dependencies and polyfills

---

src/utils.js

The original default color does not have enough contrast (4.5) with white text color.
I have updated it to compatible with WCAG AA/AAA standard (4.5:1 and 7.5:1)
#d73d32 --> #A62A21
#4285f4 --> #0B51C1
#67ae3f --> #3A6024
#d61a7f --> #A81563
#ff4080 --> #B3003C
Thanks a lot !

Accessibility fix for default color

---

index.d.ts

React 18 [removed](https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc/71809927#71809927) default children props. 
This adds children props to adjust typings for the library to work with react 18

React 18 add children to props

---

index.d.ts
src/components/image.js
src/utils.js

fix(image): allow empty string for alt and title property
