ambassify/react-avatar

avatar.js, avatar.jsx
The `Avatar` component only sets `this.state.src` and `this.state.value` right before the component is mounted. This causes the component to ignore changes in `this.props.src`, `this.props.name`, and `this.props.value`.
added the `componentWillReceiveProps` method to allow the component watch for changes in `this.props.src`, `this.props.name`, and `this.props.value` and update the state appropriately.
=> allow for changes in src, name, and value

avatar.js, avatar.jsx
changed `this.props.src` to `newProps.src`
=> minor bugfix

avatar.js, avatar.jsx, run.jsx
Gravatar should fallback to the next available option if no gravatar is available
resolves #9
=> Gravatar fallback

avatar.js, avatar.jsx, package.json
implement pure render mixin to optimize rerendering
resolves #8
=> Pure render mixin

README.md, avatar.js, avatar.jsx
=> Add fgColor property for controlling text

avatar.js, avatar.jsx
It was replaced in https://github.com/Sitebase/react-avatar/pull/20
=> Use lowercase md5 module in reuqire.

README.md, build/demo.js, lib/demo.js, lib/index.js, lib/sources/Vkontakte.js, lib/utils.js, src/demo.js, src/index.js, src/sources/Twitter.js, src/sources/Vkontakte.js, src/utils.js
**TODO**: Improve `fetchJSONP` onerror handler: it not working properly on IE8 and below
=> Added vk.com (Vkontakte) source support

build/demo.js, lib/index.js, package.json, src/index.js
resolves https://github.com/Sitebase/react-avatar/issues/32
resolves https://github.com/Sitebase/react-avatar/issues/31
=> Use shallow compare instead of pure render mixin

lib/index.js, src/index.js
=> Fixed fetch async issue

package.json
This PR updates dependencies, so React-Avatar works with React 15.
=> Update dependencies for React 15

build/demo.js, lib/demo.js, lib/index.js, lib/sources/Facebook.js, lib/sources/Google.js, lib/sources/Value.js, lib/utils.js, src/index.js
=> setting initial src value in constructor

README.md, src/index.js
Added onClick property, and description for it in Readme.md.
=> Add onClick property.

README.md, build/demo.js, lib/demo.js, lib/index.js, lib/sources/Facebook.js, lib/sources/Google.js, lib/sources/Value.js, package-lock.json, src/demo.js, src/index.js, src/sources/Value.js
If maxInitials is set to 2 and the name is Foo Bar Barsson the initials will be FB. This addresses issue #50.
=> maxInitials prop that declares how many initials should be displayed.

lib/utils.js, src/utils.js
Quick fix for LocalStorage checks
1. function _hasLocalStorage() was never called on line 73 (missing function call ())
2. function hasSourceFailedBefore never checked for LS
3. _hasLocalStorage function failed with Access is denied Error when localStorage is disabled (privacy mode vs disabled in browser settings)
=> Fix localStorage checks / access is denied errors

build/demo.js, lib/demo.js, lib/index.js, lib/utils.js, src/index.js
Should have been part of https://github.com/Sitebase/react-avatar/pull/94
=> [size] fix prop-type for size property

src/demo.js, src/index.js
=> [alignment] Align all avatar types the same.

build/demo.js, lib/demo.js, lib/sources/Value.js, src/demo.js, src/sources/Value.js
I found that when you have users with the same initials it's useful to have a different color to differentiate them.
With this change the color is generated from the email (if available) or the name, so that users with the same initials have different colors.
I also added to the demo file to show how this works.
=> Different colors for the same initials

README.md, build/demo.js, lib/demo.js, lib/index.js, lib/utils.js, src/demo.js, src/index.js, src/utils.js
expose the algorithm used internally to pick random colors from an
array.
The algorithm itself has been updated to use a [Linear congruential generator](https://en.wikipedia.org/wiki/Linear_congruential_generator)
Related to https://github.com/Sitebase/react-avatar/pull/67
=> [getRandomColor] export random color generation

.eslintrc, package.json, src/demo.js, src/utils.js
Linting was only enabled on `src/index.js`, run `eslint` against the
entire `src` directory and enable the `no-console` rule.
Resolves https://github.com/Sitebase/react-avatar/issues/102
=> [eslint] fix code linting

README.md
Should be camelCase not kebab-case
=> Fix prop names

build/demo.js, lib/demo.js, lib/index.js, lib/sources/Facebook.js, lib/sources/Google.js, lib/sources/Gravatar.js, lib/sources/Skype.js, lib/sources/Src.js, lib/sources/Twitter.js, lib/sources/Value.js, lib/sources/Vkontakte.js, package.json, src/demo.js, src/index.js, src/sources/Facebook.js, src/sources/Google.js, src/sources/Gravatar.js, src/sources/Skype.js, src/sources/Src.js, src/sources/Twitter.js, src/sources/Value.js, src/sources/Vkontakte.js
Did a cleanup of source selection
Should resolve
- https://github.com/Sitebase/react-avatar/issues/51
- https://github.com/Sitebase/react-avatar/issues/49
=> [sources] Simplify avatar update logic

build/demo.js, lib/demo.js, lib/index.js, lib/sources/Facebook.js, lib/sources/Google.js, lib/sources/Gravatar.js, lib/sources/Icon.js, lib/sources/Skype.js, lib/sources/Src.js, lib/sources/Twitter.js, lib/sources/Value.js, lib/sources/Vkontakte.js, src/demo.js, src/index.js, src/sources/Facebook.js, src/sources/Google.js, src/sources/Gravatar.js, src/sources/Icon.js, src/sources/Skype.js, src/sources/Src.js, src/sources/Twitter.js, src/sources/Value.js, src/sources/Vkontakte.js
The outer element will now receive a className based on the source that is
currently showing.
Resolves https://github.com/Sitebase/react-avatar/issues/52
=> [sources] add source classname to avatar

build/demo.js, lib/index.js, lib/internal-state.js, src/index.js, src/internal-state.js
Resolves https://github.com/Sitebase/react-avatar/issues/112
=> [fetch] fix fetch calling setState when not mounted

lib/sources/Icon.js, src/sources/Icon.js
Resolves https://github.com/Sitebase/react-avatar/issues/116
=> [sources][icon] fix icon background color

build/demo.js, lib/demo.js, lib/sources/Icon.js, lib/sources/Value.js, src/demo.js, src/sources/Icon.js, src/sources/Value.js
Resolves https://github.com/Sitebase/react-avatar/issues/122
=> [icon][value] Re-render when color prop updates

demo/index.js, src/index.js
Resolves https://github.com/Sitebase/react-avatar/issues/133
=> [text] Set scaling correctly when previous sacling was applied

src/index.js
Resolves https://github.com/Sitebase/react-avatar/issues/142
=> [text scaling] resolves scaling issue in IE11 (#142)

src/avatar.js
Resolves https://github.com/Sitebase/react-avatar/issues/167
=> [avatar] Resize initials when size is changed

src/avatar.js
This fixes an inconsistency introduce in https://github.com/Sitebase/react-avatar/pull/176
=> [title] make title prop consistent

index.d.ts
Resolves https://github.com/Sitebase/react-avatar/issues/189
=> [typescript][cache] add better definitions

src/avatar.js, src/utils.js
Resolves https://github.com/Sitebase/react-avatar/issues/185
=> [initials] Replace uppercase CSS by JS uppercase

demo/index.js, src/context.js
Resolves https://github.com/Sitebase/react-avatar/issues/201
=> [config] forward ref if support by current version

demo/index.js, src/components/image.js, src/components/text.js
Resolves https://github.com/ambassify/react-avatar/issues/240
=> fix(round): support number in proptypes

.github/workflows/test-node.yaml, .github/workflows/tests.yaml
Resolves https://github.com/ambassify/react-avatar/issues/232
=> feat(test): add github actions

package.json, webpack.config.js
Related to https://github.com/ambassify/react-avatar/issues/237
=> fix(demo): upgrade webpack to prevent segfault
